---
title: "Cursos"
---


*2022* Economía ambiental y ecológica del agua. Maestría Gestión integral del agua.
*Semestre 2022-01*  
Colef Monterrey 

*2022* Introducción a la Economía. Maestría en Acción pública y Desarrollo Social. 
*Semestre 2022-01*  
Colef Ciudad Juárez

*2022* Estadística I. Maestría en Desarrollo Regional. 
*Semestre 2022-01*  
Colef Tijuana.

*2019* Estadística II. Maestría en Estudios de Población. 
*Semestre 2019-02*  
Colef Tijuana.

*2018* Teoría Económica. Maestría en Desarrollo Regional.       *Semestre 2018-01* 

*2018* Economía Ambiental y Ecológica el Agua. 
Maestría en gestión Integral del Agua. *Semestre 2018-01*
[MAGIA-101-EAyEA-2018]()


*2018* Teoría Económica.  Maestría en Desarrollo Regional.       *Semestre 2018-01* 

Colef Tijuana.

*2018* Economía Ambiental y Ecológica el Agua. 
Maestría en gestión Integral del Agua. *Semestre 2018-01*
[MAGIA-101-EAyEA-2018]()  

Colef Monterrey.


*2017* Instrumentos económicos para la gestión de los recursos hídricos
Maestría en gestión Integral del Agua. *Semestre 2017-01*

*2017* Sistemas Integrados de información de Tierra y Agua
Maestría en gestión Integral del Agua. *Semestre 2017-01*

*2016* Seminario de Titulación II
Maestría en gestión Integral del Agua. *Semestre 2016-01*

*2016* Seminario de Tesis
Maestría en Economía Aplicada.         *Semestre 2016-01*

*2016* Propedéutico Estadística
Maestría en gestión Integral del Agua. *Semestre 2016-02*


Colef Monterrey

*2017* Sistemas Integrados de información de Tierra y Agua
Maestría en gestión Integral del Agua. *Semestre 2017-01*

Colef Monterrey

*2016* Seminario de Titulación II
Maestría en gestión Integral del Agua. *Semestre 2016-01*

Colef Monterrey

*2016* Seminario de Tesis
Maestría en Economía Aplicada.         *Semestre 2016-01*

Colef Tijuana

*2016* Propedéutico Estadística
Maestría en gestión Integral del Agua. *Semestre 2016-02*

Colef Monterrey


*2015* Instrumentos económicos para la gestión de los recursos hídricos.
Maestría en gestión Integral del Agua. *Semestre 2015-01*

*2015* Econometría II
Maestría en Economía Aplicada.         *Semestre 2015-02*

## Summer Data Science Workshop.

**2018**  Herramientas de análisis Estadístico

Colef Monterrey


*2015* Econometría II
Maestría en Economía Aplicada.         *Semestre 2015-02*

Colef Tijuana



## Summer Data Science Workshop.

**2018**  Herramientas de análisis Estadístico.



## Estancias Académicas

Visiting Scholar
University of Technology Sydney, Australia. **2009**
Supervisor: Associate Professor Dr. Beatriz carrillo García y Yingjie Guo
Yingjie.Guo@uts.edu.au  

Estancia académica de investigación en el marco de la formación de consorcios  de centros públicos de investigación.
**Lugar:** Centro de Investigación y Docencia Económicas **CIDE** **2017**

Estancia Academica de investigación Economía Aplicada en la línea Economía Medio Ambiente Salud. 
**Lugar:** Centro de Investigación y Docencia Económicas **CIDE** **2018**

Estancia Académica de investigación. Linea de investigación  manejo de datos.  **Lugar:**
Centro de Investigación e Innovación en Tecnologías de la Información y Comunicación **INFOTEC**. **2019**

### Recent Talks.

**2019** Universidad Caltólica de Temuco, **Chile**. 
Laboratorio de planificación territorial.  
XL Congreso Nacional y XXV Internacional de Geografía.

**2018** Universidad Iberoamericana, Puebla.
8° Congreso Latinoamericano de Población. 


**2017**  Universidad de La Frontera. Temuco, **Chile**
XXXVIII Congreso Nacional y XXIII Internacional de Geografía.





